spring:
  application:
    name: gateway-service  
  cloud:
    gateway:
      routes:
      - id: company-service
        uri: lb://company-service
        predicates:
        - Path=/api/v1.0/market/company/**
      - id: company-service
        uri: lb://stock-service
        predicates:
        - Path=/api/v1.0/market/stock/**  
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
server: 
  port: 8200